# reference:
# https://github.com/DNSCrypt/dnscrypt-proxy/blob/master/dnscrypt-proxy/example-dnscrypt-proxy.toml

# listen on port 53, all interfaces
listen_addresses = [ '0.0.0.0:53' ]

# use the following DoH providers from the 'public-resolvers' list;
# see the URL below for details, add the names here...
# 1/ https://dnscrypt.info/public-servers
# 2/ https://download.dnscrypt.info/resolvers-list/v2/public-resolvers.md
server_names = ['a-and-a', 'cloudflare', 'cloudflare-onion', 'dnslify-doh', 'google', 'iij', 'nextdns', 'powerdns-doh', 't53'] 
disabled_server_names = []

# poll/log every hour
cert_refresh_delay = 60

# limits
max_clients = 250

# what kinds of server do we want to resolve from?
doh_servers = true
ipv4_servers = false
ipv6_servers = false
dnscrypt_servers = false

# imma going to assume IPv4 only, feel free to tweak if you are IPv6-capable
block_ipv6 = true

# don't let weird queries & typos leak upstream
block_unqualified = true
block_undelegated = true

# the goal of using tor is to not care about server logging, so why limit ourselves?
require_nolog = false

# but we *do* want integrity
require_dnssec = true

# and we probably want DoH servers that advertise themselves as unfiltered
require_nofilter = true

# use tor
force_tcp = true
proxy = 'socks5://127.0.0.1:9050'
reject_ttl = 600
timeout = 10000
keepalive = 1

# loadbalancing
lb_strategy = 'p2'
lb_estimator = true

# logging
log_level = 2
use_syslog = true
log_files_max_size = 64
log_files_max_age = 7
log_files_max_backups = 4

# less linkability / more privacy (at slight performance impact)
tls_disable_session_tickets = true
tls_cipher_suite = [52392, 49199]

# this server needs to be able to probe the internet, so it's the only
# one which can use port 53 and DNSCrypt-proxy only uses these in
# limited circumstances...
fallback_resolvers = ['1.1.1.1:53', '8.8.8.8:53']
ignore_system_dns = true
netprobe_timeout = 60
netprobe_address = '8.8.8.8:53'

# caching
cache = true
cache_size = 4096
cache_min_ttl = 2400
cache_max_ttl = 86400
cache_neg_min_ttl = 60
cache_neg_max_ttl = 600

# no i am not configuring this resolver as a local DoH listener,
# to do so requires a TLS certificate and that's a whole other
# world of pain.

[query_log]
file = '/var/log/dnscrypt-proxy/query.log'

[nx_log]
file = '/var/log/dnscrypt-proxy/nx.log'

[sources]
[sources.'public-resolvers']
url = 'https://download.dnscrypt.info/resolvers-list/v2/public-resolvers.md'
cache_file = '/var/cache/dnscrypt-proxy/public-resolvers.md'
minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
refresh_delay = 72
prefix = ''

# if you want to experiment with the Cloudflare DoH-over-Onion,
# add 'cloudflare-onion' as a provider...
# https://developers.cloudflare.com/1.1.1.1/fun-stuff/dns-over-tor/
[static]
[static.'cloudflare-onion']
stamp = 'sdns://AgcAAAAAAAAAAAA-ZG5zNHRvcnBubGZzMmlmdXoyczJ5ZjNmYzdyZG1zYmhtNnJ3NzVldWozNXBhYzZhcDI1emdxYWQub25pb24KL2Rucy1xdWVyeQ'
